#+TITLE:HW7
#+AUTHOR:Martin Fracker
1) Needs to show each step of the algorithm. See tables below.
2) Ack packets will not be subjected to the same congestion that data packets
   may be exposed to making it less likely that the sender will timeout for a
   particular data packet.
3) Faster recovery due to relatively shorter RTT on wireless link $BD$. Not
   reacting too aggressively due to errors may reduce overhead on wireless link $BD$.
4) 
   1) [1,6] slow start
   2) [6,16], [17,22] avoidance
   3) The cwd is cut in half which indicates a triple dupack.
   4) sstresh is initialized to its maximum value, in this example it looks like
      that maximum value is 32 segments
   5) 21 (in otherwords half of what the cwnd was before the triple dupack)
   6) 13 (in otherwords half of what the cwnd was before the timeout)
   7) The first 63 segments are sent during the first 16 transmission rounds. In
      the 17th transmission round 33 more segments will be transmitted, one of
      them being the 70th segment.
   8) cwnd will be set to 4, and ssthresh will save the old cwnd, 8.
5) An advantage is not having to go through the process of slow start once
   again. A disadvantage is that the wireless link may have changed in quality
   increasing the likelihood of massive congestion. To get around this, set the
   cwnd to 1 and save the old cwnd in sstresh. After the transmission round, increase
   the cwnd to half of the old cwnd. After the transmission round, increase to
   75% of the old cwnd. After the transmission round, increase to 87.5% of the
   old cwnd. Assuming that the link did not change in quality, increasing the
   cwnd back to 100% of the old cwnd in the next round should be fine. This
   solves the problem of normal slow start taking too long, but doesn't
   immediately jump back up to the old cwnd in case the quality of link went down.
| Destination | next-hop | cost |
|-------------+----------+------|
| A           | *        |  0   |
| B           | B        |  4   |
| C           | D        |  6   |
| D           | D        |  4   |
| E           | D        |  10  |

| Destination | next-hop | cost |
|-------------+----------+------|
| A           | A        |  4   |
| B           | C        |  4   |
| C           | C        |  2   |
| D           | *        |  0   |
| E           | C        |  6   |
